#PARSER CONFIGURATION
config_PATH: parser_config/sites_config_css_nav.yml
xlink_WORKING_FOLDER: xlink_dir/

smtp_host: sparkbrains.pp.ua
smtp_port: 465
mail_username: admin@sparkbrains.pp.ua
mail_password: d26011986
mail_email_from: admin@sparkbrains.pp.ua

#DATABASE CONFIGURATION
#database:
#  driverClass: org.h2.Driver
#  user: Denis
#  password: d26011986
#  url: jdbc:h2:tcp://localhost/~/genres
#  validationQuery: "/* MyApplication Health Check */ SELECT 42"
#  properties:
#    charSet: UTF-8

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: streletsdy
  password: 1111
  url: jdbc:mysql://localhost/FilmixDB?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  validationQuery: "/* MyApplication Health Check */ SELECT 42"
#  properties:
#    charSet: UTF-8
#    hibernate.hbm2ddl.auto: update

#SERVER CONFIGURATION
server:
  requestLog:
    appenders:
      - type: console
        timeZone: system

  applicationConnectors:
    - type: http
      port: 8020
  adminConnectors:
    - type: http
      port: 8021

#SUNDIAL SCHEDULER CONFIGURATION
sundial:
  thread-pool-size: 10
  shutdown-on-unload: true
  start-delay-seconds: 0
  start-scheduler-on-load: false
  global-lock-on-load: false
  annotated-jobs-package-name:
  tasks: [startjob, stopjob, addjob, removejob, startschedulerpackage, startscheduler, stopscheduler, pausescheduler]

#LOGGER CONFIGURATION
logging:
  level: INFO
  loggers:
    com.denspark.spring: INFO
    org.hibernate.SQL: INFO
    #org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction: INFO
    org.springframework.security.web.FilterChainProxy: DEBUG
    logging.level.org.springframework.security: DEBUG
    #    logging.level.org.springframework: DEBUG
    org.eclipse.jetty: INFO


  appenders:
    - type: console
      timeZone: system

    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: system
      maxFileSize: 10MB

# the key needs to match the configuration key of the renderer (ViewRenderer::getConfigurationKey)
viewRendererConfiguration:
  freemarker:
    strict_syntax: yes
    whitespace_stripping: yes
  mustache:
    cache: false

hibernateProperties:
  #  hibernate.dialect:
  hibernate.show_sql: false
  hibernate.format_sql: true
  hibernate.use_sql_comments: true
  hibernate.use_identifier_rollback: true
  hibernate.hbm2ddl.auto: none

  hibernate.connection.CharSet: utf8
  hibernate.connection.characterEncoding: utf8
  hibernate.connection.useUnicode: true

  hibernate.cache.use_second_level_cache: true
  hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

  hibernate.cache.use_query_cache: true

cinemixConfig:

  films_genres_exclude: [
    реальное тв,
    короткометражка,
    документальный,
    музыка,
    биография,
    аниме,
    новости,
    ток-шоу,
    для взрослых,
    концерт,
    игра,
    фильм-нуар,
    церемония,
    сериалы,
    мультсериалы,
    передачи c тв,
    дорамы,
    ситком,
    оригинал,
    тв сериалы ]

  tv_series_genres_exclude: [
    короткометражка,
    документальный,
    музыка,
    биография,
    аниме,
    спорт,
    новости,
    ток-шоу,
    для взрослых,
    концерт,
    игра,
    фильм-нуар,
    церемония,
    мультсериалы,
    дорамы,
    ситком ]

  tv_series_genre: [
    сериалы,
    мультсериалы,
    дорамы,
    ситком,
    тв сериалы ]