#PARSER CONFIGURATION

config_PATH: parser_config/sites_config_css_nav.yml
xlink_WORKING_FOLDER: xlink_dir/

#DATABASE CONFIGURATION
#database:
#  driverClass: org.h2.Driver
#  user: Denis
#  password: d26011986
#  url: jdbc:h2:tcp://localhost/~/genres
#  validationQuery: "/* MyApplication Health Check */ SELECT 42"
#  properties:
#    charSet: UTF-8
database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: streletsdy
  password: 1111
  url: jdbc:mysql://localhost/FilmixDB?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  validationQuery: "/* MyApplication Health Check */ SELECT 42"
  properties:
    charSet: UTF-8
#    hibernate.hbm2ddl.auto: mergeAndClear

#SERVER CONFIGURATION
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    com.denspark.spring: DEBUG
    org.hibernate.SQL: INFO
    org.springframework.transaction: INFO

  appenders:
    - type: console

    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB