articleItemSelector: '#dle-content > article'
articleItemURLSelector: '#dle-content > article > div.short > a'
articleLastPageSelector: '#dle-content>div>a:nth-last-child(2)'
articleListLastPageIndex: 4774
cartoonCategorySelector: '#header > div > nav > ul > li:nth-child(3) > div > ul:nth-child(n+2)
  > li a[href]'
cartoonListLastPageIndex: 246
cartoonListLastPageSelector: '#dle-content>div>a:nth-last-child(2)'
cartoonListUrl: http://filmix.cc/multfilmy
categoryListElementSelector: '#header>div>nav>ul>li:nth-child(1)>div>ul:gt(0)>li>a'
categoryListElementUrlAttr: href
durationElementKey: class
durationElementRegex: duration
fileExtension: .html
filmCategorySelector: '#header > div > nav > ul > li:nth-child(1) > div > ul:nth-child(n+2)
  > li a[href]'
filmListLastPageIndex: 3783
filmListLastPageSelector: '#dle-content>div>a:nth-last-child(2)'
filmListUrl: http://filmix.cc/films
name: Filmix
pageQuerySeparator: page
personItemURLSelector: '#dle-content > article > div.short > a'
personListLastPageIndex: 9911
personListLastPageIndexSelector: '#dle-content > div > div > div > div > a:nth-child(6)'
personsSectionUrl: http://filmix.cc/persons
ratingElementKey: class
ratingElementRegex: rating
saveDir: files/sites/tmp_html
separator: /
serialCategorySelector: '#header > div > nav > ul > li:nth-child(2) > div > ul:nth-child(n+2)
  > li a[href]'
serialListLastPageIndex: 721
serialListLastPageSelector: '#dle-content>div>a:nth-last-child(2)'
serialListUrl: http://filmix.cc/serialy
thumbnailAbsUrlKey: src
thumbnailUrlKey: class
thumbnailUrlRegex: thumbnails
url: http://filmix.cc
videoAbsUrlKey: href
videoSrcElementAttrKey: value
videoSrcElementsKey: class
videoSrcElementsRegex: player2-container
videoTitleKey: class
videoTitleRegex: videotitle
